import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Layouts/Footer";
import MainHeader from "@/components/Layouts/Header";
import Topline from "@/components/Layouts/topline";
import SocialIcons from "@/components/Layouts/SocailIcon";
import ScrollToTopButton from "@/components/Layouts/ScrollerTop";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sell-Pixers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header class="">
          <Topline/>
          <MainHeader/>
       
        </header>
        <main className="min-h-screen">{children}</main>
        <Footer/>
        <SocialIcons/>
        <ScrollToTopButton/>
      </body>
    </html>
  );
}
